name: Auto Update M3U to JSON

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘণ্টার শুরুতে ট্রাই করবে
  workflow_dispatch: # ম্যানুয়ালি রান করার বোতাম

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Script
        run: node fetch_to_json.js

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add playlist.json
          git commit -m "Auto updated playlist.json at $(date -u)" || echo "No changes to commit"
          git push
