Name: Auto Update M3U to JSON

on:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর অটো রান হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Script
        run: node fetch_to_json.js

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto updated playlist.json [skip ci]" && git push)
