name: Auto Update Toffee Playlist

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর অটো রান হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Script
        run: python script.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto updated Toffee playlist" || exit 0
          git push
