name: Auto Generate Playlists

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Install Chrome Browser for Puppeteer
        run: |
          npx puppeteer browsers install chrome

      - name: Run index.js to Generate Playlists
        run: node index.js

      - name: Commit and Push Updated Playlists
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add circle.m3u circle.json
          git commit -m "Auto-update playlists [skip ci]" || exit 0
          git push
